// Show a project on the home "Our Works" row: add featured: true, year, shortTitle
const PROJECTS = [
  {
    id: 'MVPA60',
    featured: true,
    year: '2025',
    shortTitle: 'MVPA60',
    title: 'EDB_MVPA60@運動好習慣 從小開始',
    client: 'Education Bureau (EDB)',
    nature: 'Promotional Video',
    duration: '5 mins',
    cover: 'assets/BH/images/Showcase/Video/Project-V02/Cover-V02.webp',
    videoUrl: 'https://emm.edcity.hk/media/MVPA60%40%E9%81%8B%E5%8B%95%E5%A5%BD%E7%BF%92%E6%85%A3+%E5%BE%9E%E5%B0%8F%E9%96%8B%E5%A7%8B+%28%E4%B8%AD%E3%80%81%E8%8B%B1%E6%96%87%E5%AD%97%E5%B9%95%E5%8F%AF%E4%BE%9B%E9%81%B8%E6%93%87%29/1_hj3wp4i5',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      '2D Motion Graphic',
      'Graphic Design',
      'Photo Editing',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      'Video Shooting',
    ],
  },
  {
    id: 'siemens-tvb',
    featured: true,
    year: '2026',
    shortTitle: 'Siemens',
    title: 'Siemens TVB',
    client: 'TVB',
    nature: 'Siemens',
    duration: '30 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V01/Cover-V01.webp',
    videoUrl: 'https://www.youtube.com/watch?v=9UlSwBps8-g',
    services: [
      '2D Motion Graphic',
      'Graphic Design',
      'Photo Editing',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      'Video Shooting',
      'Producing',
      'Art Direction',
      'Set Design',
    ],
  },
  {
    id: 'project-v03',
    featured: true,
    year: '2024',
    shortTitle: '機場購物攻略',
    title: '機場直播最後召集：洪永城和郭柏妍與您分享機場購物攻略',
    client: 'Airport Authority Hong Kong / Hong Kong International Airport',
    nature: 'TVC',
    duration: '30 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V03/Cover-V03.webp',
    videoUrl: 'https://youtu.be/_RTivqNG2mQ?si=9vUf-1ScfsS86KEu',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
    ],
  },
  {
    id: 'project-v04',
    title: 'Prof. Erin Cho, Limin Professor in Integrated Strategies and Leadership in Fashion',
    client: 'The Hong Kong Polytechnic University (PolyU)',
    nature: 'Profile Video',
    duration: '2 mins 10 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V04/Cover-V04.webp',
    videoUrl: 'https://youtu.be/wSeZHcAqsYw?si=BUmO7sQuPWrJ2zXD',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
    ],
  },
  {
    id: 'project-v05',
    title: "CityUHK New Year's Day Flag-Raising Ceremony 2026",
    client: 'City University of Hong Kong (CityUHK)',
    nature: 'Event Video',
    duration: '1 min 29 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V05/Cover-V05.webp',
    videoUrl: 'https://youtu.be/doAeVqT5gro?si=9NxJ2cDav6R2d2Jd',
    services: [
      'Multicam Shooting (Live)',
      'Panel Directing',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
    ],
  },
  {
    id: 'project-v06',
    title: '【星級用家】林子善，大善NMN20000PLUS+，善待身體，善待家人。',
    client: '日本大善 / 大善製藥 DAIZEN',
    nature: 'TVC',
    duration: '1 min 3 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V06/Cover-V06.webp',
    videoUrl: 'https://youtu.be/bojWpoyABhY?si=IDqFBn7lI-bDOIZh',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
    ],
  },
  {
    id: 'project-v07',
    title: '日本大善 NMN 20000 Plus+ (蔡潔)',
    client: '日本大善 / 大善製藥 DAIZEN',
    nature: 'TVC',
    duration: '20 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V07/Cover-V07.webp',
    videoUrl: 'https://youtu.be/qQPL6zweW6k?si=uAIjkH3Wd3FZxkex',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
    ],
  },
  {
    id: 'project-v08',
    title: '【維特健靈幫你掌握健康 使大家未病防病 有病防傳】',
    client: 'Vita Green 維特健靈',
    nature: 'Corporate Video',
    duration: '1 min',
    cover: 'assets/BH/images/Showcase/Video/Project-V08/Cover-V08.webp',
    videoUrl: 'https://youtu.be/Vfm0Jr_1ae8?si=KvYeEJ3IF7v0XATo',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
    ],
  },
  {
    id: 'project-v09',
    title: '鼓掌迎未來：資訊與通訊科技篇 [完整版]',
    client: 'The Hong Kong Jockey Club Charities Trust (The CLAP-TECH Pathway)',
    nature: 'Promotional Video',
    duration: '6 mins',
    cover: 'assets/BH/images/Showcase/Video/Project-V09/Cover-V09.webp',
    videoUrl: 'https://youtu.be/VA4muotoxN8?si=PxIKyICZH8pHZWli',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      '2D Motion Graphic',
      'Graphic Design',
    ],
  },
  {
    id: 'project-v010',
    title: '鼓掌迎未來：創意媒體篇 [完整版]',
    client: 'The Hong Kong Jockey Club Charities Trust (The CLAP-TECH Pathway)',
    nature: 'Promotional Video',
    duration: '5 mins 35 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V010/Cover-V010.webp',
    videoUrl: 'https://youtu.be/uHpuCxvLnwU?si=t6o4GS80B_f0aYm6',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      '2D Motion Graphic',
      'Graphic Design',
    ],
  },
  {
    id: 'project-v011',
    title: '多元成掌路',
    client: 'The Hong Kong Jockey Club Charities Trust (The CLAP-TECH Pathway)',
    nature: 'Promotional Video / 2D Motion Graphic',
    duration: '2 mins 25 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V011/Cover-V011.webp',
    videoUrl: 'https://youtu.be/MXw-H_RfDJw?si=1SAc9XDAWVA3SeRt',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      '2D Motion Graphic',
      'Graphic Design',
    ],
  },
  {
    id: 'project-v012',
    title: 'HKIIT Opening Video',
    client: 'Hong Kong Institute of Information Technology (HKIIT)',
    nature: '3D Mapping Animation',
    duration: '1 min 8 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V012/Cover-V012.webp',
    videoUrl: 'https://vimeo.com/995657232?share=copy&fl=cl&fe=ci',
    services: [
      '3D Mapping Animation',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
    ],
  },
  {
    id: 'project-v013',
    title: 'Equity, Diversity and Inclusion in Research',
    client: 'The Hong Kong Polytechnic University — Research and Innovation Office (PolyU RIO)',
    nature: 'Promotional Video',
    duration: '',
    cover: 'assets/BH/images/Showcase/Video/Project-V013/Cover-V013.webp',
    videoUrl: 'https://youtu.be/F1UxiTIUSpI?si=3nJPQqlczaHOjZq5',
    services: [
      'Concept & Idea',
      'Script',
      'Directing',
      'Art Direction',
      'Video Shooting',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      '2D Motion Graphic',
    ],
  },
  {
    id: 'project-v014',
    title: 'EDU The 24th Congregation',
    client: '',
    nature: 'Ceremonial videos',
    duration: '3 mins 8 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V014/Cover-V014.webp',
    videoUrl: 'https://youtu.be/PGtVF1T4pyw?si=j4hamlX6oGOBZ7cZ',
    services: [],
  },
  {
    id: 'project-v015',
    title: '土木工程拓展署_保養斜坡 保障生命',
    client: '',
    nature: 'TV APIs',
    duration: '30 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V015/Cover-V015.webp',
    videoUrl: 'https://youtu.be/Rpp9sXbLXtU?si=-AST0bdrTu_-V2dP',
    services: [],
  },
  {
    id: 'project-v016',
    title: '正向家長運動 － 大手牽小手 愉快同步走',
    client: '',
    nature: '2D Animation & Filming Video',
    duration: '30 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V016/Cover-V016.webp',
    videoUrl: 'https://youtu.be/mKDwyalwM8A?si=VVFzW3b98Ggkquih',
    services: [],
  },
  {
    id: 'project-v017',
    title: '正向家長運動—關懷鼓勵與接納 正向家庭齊建立',
    client: '',
    nature: '2D Animation & Filming Video',
    duration: '30 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V017/Cover-V017.webp',
    videoUrl: 'https://youtu.be/X_9IVS0tR6s?si=qPnPwqJ35UVjSXBH',
    services: [],
  },
  {
    id: 'project-v018',
    title: '我和「理」的故事 Our PolyU Stories',
    client: '',
    nature: 'Corporate Video',
    duration: '8 mins 1 sec',
    cover: 'assets/BH/images/Showcase/Video/Project-V018/Cover-V018.webp',
    videoUrl: 'https://youtu.be/yVrJmnxk0u0?si=wFj3uYKRAeZ4BU1q',
    services: [],
  },
  {
    id: 'project-v019',
    title: '香港青年獎勵計劃賽馬會愛丁堡公爵訓練營',
    client: '',
    nature: 'Kick off videos',
    duration: '1 min 10 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V019/Cover-V019.webp',
    videoUrl: 'https://youtu.be/zG9vC2bfUSY?si=gWiXHvMMVofBl2nN',
    services: [],
  },
  {
    id: 'project-v020',
    title: 'CUHK White Coat Inauguration Ceremony for Medical Freshmen 2025',
    client: '',
    nature: 'Highlight Video',
    duration: '3 mins 22 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V020/Cover-V020.webp',
    videoUrl: 'https://youtu.be/WrXEbX9spIs?si=IcV4WlMaoYf5ipwq',
    services: [],
  },
  {
    id: 'project-v021',
    title: 'PolyU_Young Innovative Researcher Award (YIRA) 2025',
    client: '',
    nature: 'Corporate Video',
    duration: '3 mins',
    cover: 'assets/BH/images/Showcase/Video/Project-V021/Cover-V021.webp',
    videoUrl: 'https://youtu.be/O2-XdGdro2k?si=7UaaPHLCXBKgsZkJ',
    services: [],
  },
  {
    id: 'project-v022',
    title: '香港都會大學 樂齡科技比賽 - 香港基督教服務處 展華長者日間護理中心',
    client: '',
    nature: 'Corporate videos',
    duration: '4 mins 30 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V022/Cover-V022.webp',
    videoUrl: 'https://youtu.be/Yp5YFelN8yE?si=P0DYMbAHVJRPNcU_',
    services: [],
  },
  {
    id: 'project-v023',
    title: '香港都會大學 樂齡科技比賽 - 温馨長者之家',
    client: '',
    nature: 'Corporate videos',
    duration: '4 mins 10 secs',
    cover: 'assets/BH/images/Showcase/Video/Project-V023/Cover-V023.webp',
    videoUrl: 'https://youtu.be/xmWG2ednOq8?si=foX1pza32Ax67qRO',
    services: [],
  },
  {
    id: 'project-e01',
    title: 'Deutsche Bank - Roadshow',
    client: 'Deutsche Bank',
    nature: 'Roadshow',
    cover: 'assets/BH/images/Showcase/Event/Project-E01/DBB_01.webp',
    images: [
      'assets/BH/images/Showcase/Event/Project-E01/DBB_01.webp',
      'assets/BH/images/Showcase/Event/Project-E01/DBB_02.webp',
      'assets/BH/images/Showcase/Event/Project-E01/DBB_03.webp',
      'assets/BH/images/Showcase/Event/Project-E01/DBB_04.webp',
      'assets/BH/images/Showcase/Event/Project-E01/DBB_05.webp',
      'assets/BH/images/Showcase/Event/Project-E01/DBB_06.webp',
      'assets/BH/images/Showcase/Event/Project-E01/DBB_07.webp',
      'assets/BH/images/Showcase/Event/Project-E01/DBB_08.webp',
    ],
    services: [
      'Event Management & Productions',
      'Video Recording',
      'Rosewood Hotel',
      'National Palace Museum',
    ],
  },
  {
    id: 'project-e02',
    title: 'One Step One Paw',
    client: 'Paws Hero',
    cover: 'assets/BH/images/Showcase/Event/Project-E02/OSOP_01.webp',
    images: [
      'assets/BH/images/Showcase/Event/Project-E02/OSOP_01.webp',
      'assets/BH/images/Showcase/Event/Project-E02/OSOP_02.webp',
      'assets/BH/images/Showcase/Event/Project-E02/OSOP_03.webp',
      'assets/BH/images/Showcase/Event/Project-E02/OSOP_04.webp',
    ],
    services: [
      'Overall Event Producing',
      'Event Concept & Idea',
      'Event Decoration',
      'Backdrop Design',
      'Highlight Video Editing',
    ],
  },
  {
    id: 'project-e03',
    title: 'The Chinese Occupational Association of Hong Kong — Inauguration Ceremony and Gala Dinner',
    client: 'The Chinese Occupational Association of Hong Kong',
    nature: 'Inauguration Ceremony & Gala Dinner',
    cover: 'assets/BH/images/Showcase/Event/Project-E03/TCOA_01.webp',
    images: [
      'assets/BH/images/Showcase/Event/Project-E03/TCOA_01.webp',
      'assets/BH/images/Showcase/Event/Project-E03/TCOA_02.webp',
      'assets/BH/images/Showcase/Event/Project-E03/TCOA_03.webp',
      'assets/BH/images/Showcase/Event/Project-E03/TCOA_04.webp',
    ],
    services: [
      'Overall Event Producing',
      'Backdrop Design',
      'Video Production',
      'Highlight Video Editing',
      'Photo Taking',
      'Invitation Card Design',
    ],
  },
  {
    id: 'project-ob001',
    title: '基恩敬拜禱告更新2023-25',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB001/Cover-OBS_01.webp',
    videoUrl: 'https://agwmm.org/prayerrenewal/pr-posts/',
    services: [],
  },
  {
    id: 'project-ob002',
    title: '讚美之泉音樂事工_2025 巡迴',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB002/Cover-OBS_02.webp',
    videoUrl: 'https://sop.org/gallery/2025-tour-%e9%a6%99%e6%b8%af/',
    services: [],
  },
  {
    id: 'project-ob003',
    title: '2023 香港麥當勞叔叔之家慈善基金慈善晚宴 RMHCHK Gala Dinner',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB003/Cover-OBS_03.webp',
    videoUrl: 'https://youtu.be/Sdlec-dvRXw?si=tjLs2WBtx7JJm3CB',
    services: [],
  },
  {
    id: 'project-ob004',
    title: '城大舉行國慶升旗儀式 慶祝中華人民共和國成立76周年',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB004/Cover-OBS_04.webp',
    videoUrl: 'https://youtu.be/iDdBKro5_m8?si=PCz3qcYauJur2IYg',
    services: [],
  },
  {
    id: 'project-ob005',
    title: 'EdUHK 2024/25 Academic Inauguration and Flag-Raising Ceremony',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB005/Cover-OBS_05.webp',
    videoUrl: 'https://youtu.be/37K7nUlnisc?si=vTEP1heeLjauoXvr',
    services: [],
  },
  {
    id: 'project-ob006',
    title: 'Hong Kong Football Club',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB006/Cover-OBS_06.webp',
    videoUrl: 'https://www.youtube.com/live/RJ8R04RUi8A?si=stwkko6zMk6SKk-2',
    services: [],
  },
  {
    id: 'project-ob007',
    title: '同福堂聖誕崇拜',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB007/Cover-OBS_07.webp',
    videoUrl: 'https://www.facebook.com/photo/?fbid=654572570256516&set=pcb.622930193420754',
    services: [],
  },
  {
    id: 'project-ob008',
    title: 'Sony Chan棟篤笑2024《咁至係香港》',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB008/Cover-OBS_08.webp',
    services: [],
  },
  {
    id: 'project-ob009',
    title: '香港全民閱讀日—中小學聯校共讀半小時',
    client: '',
    nature: 'OB Shooting',
    cover: 'assets/BH/images/Showcase/OB-shooting/Project-OB009/Cover-OBS_09.webp',
    services: [],
  },
];
