const PROJECTS = [
  {
    id: 'MVPA60',
    title: 'MVPA60',
    client: 'EDB',
    nature: 'Siemens',
    duration: '5 mins Video',
    cover: 'assets/images:/Showcase:/Video:/Project-V01/Cover-V02.webp',
    videoUrl: 'https://emm.edcity.hk/media/MVPA60%40%E9%81%8B%E5%8B%95%E5%A5%BD%E7%BF%92%E6%85%A3+%E5%BE%9E%E5%B0%8F%E9%96%8B%E5%A7%8B+%28%E4%B8%AD%E3%80%81%E8%8B%B1%E6%96%87%E5%AD%97%E5%B9%95%E5%8F%AF%E4%BE%9B%E9%81%B8%E6%93%87%29/1_hj3wp4i5',
    services: [
      '2D motion graphic',
      'Graphic and Network',
      'Photos Editing',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      'Video Shooting',
      'Producing',
      'Art Direction',
      'Set Design',
    ],
  },
];
  {
    id: 'siemens-tvb',
    title: 'Siemens × TVB',
    client: 'TVB',
    nature: 'Siemens',
    duration: '30 Seconds Video',
    cover: 'assets/images:/Showcase:/Video:/Project-V01/Cover-V01.webp',
    videoUrl: 'https://www.youtube.com/watch?v=9UlSwBps8-g',
    services: [
      '2D motion graphic',
      'Graphic and Network',
      'Photos Editing',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      'Video Shooting',
      'Producing',
      'Art Direction',
      'Set Design',
    ],
  },
  {
    id: 'MVPA60',
    title: 'MVPA60',
    client: 'EDB',
    nature: 'Siemens',
    duration: '5 mins Video',
    cover: 'assets/images:/Showcase:/Video:/Project-V01/Cover-V02.webp',
    videoUrl: 'https://emm.edcity.hk/media/MVPA60%40%E9%81%8B%E5%8B%95%E5%A5%BD%E7%BF%92%E6%85%A3+%E5%BE%9E%E5%B0%8F%E9%96%8B%E5%A7%8B+%28%E4%B8%AD%E3%80%81%E8%8B%B1%E6%96%87%E5%AD%97%E5%B9%95%E5%8F%AF%E4%BE%9B%E9%81%B8%E6%93%87%29/1_hj3wp4i5',
    services: [
      '2D motion graphic',
      'Graphic and Network',
      'Photos Editing',
      'Online Editing',
      'Colour Grading',
      'Audio Mixing',
      'Video Shooting',
      'Producing',
      'Art Direction',
      'Set Design',
    ],
  },
];
